on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  set-stage-var:
    runs-on: ubuntu-latest
    steps:
      - name: set for dev
        if: contains(${{ inputs.environment }}, 'dev')
        run: |
          echo "STAGE=dev" >> $GITHUB_ENV
      - name: set for staging
        if: contains(${{ inputs.environment }}, 'staging')
        run: |
          echo "STAGE=staging" >> $GITHUB_ENV
    
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.print_tags == true }} 
    name: Deploy app to ${{ inputs.environment }}
    steps:
      - name: Print the input tag to STDOUT
        run: | 
          echo  The tags are ${{ inputs.tags }} 
          echo  The STAGE is $STAGE
